### ISSUE TITLE
Error when clicking "join bike community"

### ISSUE THREAD

**Issue by joeitu** [OpenHospitalityNetwork/ohn-solid#15]
Hello, 

After logged in with my solidcommunity.net account and when clicking the 'join' button of the bike community, I get the following error:

```
HttpErrorResponse
[403 Origin Unauthorized]
<!doctype html><html><head><meta charset="utf-8"/><title>Solid Data Browser</title><script>document.addEventListener('DOMContentLoaded', function() {
        panes.runDataBrowser()
      })</script><link href="/mash.css" rel="stylesheet"></head><body class="db-layout"><header class="db-layout__header header" id="PageHeader"></header><div class="TabulatorOutline db-layout__content" id="DummyUUID" role="main"><table id="outline"></table><div id="GlobalDashboard"></div></div><footer class="db-layout__footer" id="PageFooter"></footer><script src="/mashlib.min.js"></script></body></html>
```

**Comment by mrkvon** [comment]
@joeitu Thank you for reporting! The issue should be fixed now.

Can you check that you're able to join? Then i would close this.

_What happened?_
It seems that people of [OHN](https://openhospitality.network) decided to move this project from https://sleepy.bike to https://solid.openhospitality.network recently.

Due to Solid's access control design, the [Solid Pod that stores the list of community members](https://mrkvon.inrupt.net/hospex/sleepy-bike/) didn't allow the app on the new domain to access or edit the list. Hence the 403 error you experienced.

_On a side note:_ the location of the bicycle community data https://mrkvon.inrupt.net/hospex/sleepy-bike/ leaves a lot to be desired. E.g. I'm in control of that pod, therefore i have power to edit/destroy the list of the community members. Such a list, if the network grows, should be controlled by an organization. On the other hand, thanks to Solid, those are the only data that i or an organization can ruin. Members are in full control of their profile, connections (if implemented) and the rest of their data

**Comment by joeitu** [comment]
Working now! thanks :)

**Comment by mariha** [comment]
Thanks @mrkvon for taking care of this and sorry for not discussing with you the domain change. 

I'd love to catch up on OHN (and other stuff going on) with you!

**Comment by mariha** [comment]
@mrkvon can we change it back, please?

I'd like to return to sleepy.bike based on SOLID. This app solves at least one of the problems that brought us here (after WarmShowers.org changed the direction under the new board) - data lost as a result of deleted accounts. I'll try to slowly grow it to something sufficient yet fully functional.

> _On a side note_: the location of the bicycle community data https://mrkvon.inrupt.net/hospex/sleepy-bike/ leaves a lot to be desired. E.g. I'm in control of that pod, therefore i have power to edit/destroy the list of the community members. Such a list, if the network grows, should be controlled by an organization. 

Can we move that data to the pod I'd create for sleepy.bike (alternatively ohn) and grant access to that pod to a few people from ohn (you, me, maybe someone else)? Do you know maybe if changes to that list would be traceable - in a way that everyone can see _when_ and _who_ made _what_ changes?

**Comment by mrkvon** [comment]
@mariha 

> can we change it back, please?

Now, both domains will work, so you can choose where you wish to host it. :)

> Can we move that data to the pod I'd create for sleepy.bike (alternatively ohn) and grant access to that pod to a few people from ohn?

Yes, we can. Unfortunately that'll break the url of the community, which people keep in their personal pod. Fixing it will require a little thought. Ideally there would be a redirect from the old url to the new one, but i don't know if that's possible with Solid.

Ultimately, i think a dedicated server (not a solid pod) should/shall be built for this purpose. So people could e.g. remove themselves, search others by location, etc. But that would still be a centralized solution (which the current list is, too...), and somebody or some organization would control the list. So, more ultimately, we could figure out a decentralized solution of keeping the list of community members (which i don't even have a concept of in my head at the moment).
I've built a [similar index for another Solid project](https://github.com/ditup/solid-index). So maybe something along those lines. But it could be very different, too.

> Do you know maybe if changes to that list would be traceable - in a way that everyone can see when and who made what changes?

No, if it's hosted on Solid, afaik. If there is a custom service, it could be implemented, for sure. But there always tends to be some superadmin, who can e.g. edit database directly.

> I'll try to slowly grow it to something sufficient yet fully functional.

That would be really nice, if this thing is useful eventually. I have it on my someday/maybe list, too; no promises though...
